wandb_version: 1

env:
  desc: null
  value: hopper-medium-v0
max_traj_length:
  desc: null
  value: 1000
replay_buffer_size:
  desc: null
  value: 1000000
seed:
  desc: null
  value: 42
device:
  desc: null
  value: cuda
save_model:
  desc: null
  value: false
policy_arch:
  desc: null
  value: 256-256
qf_arch:
  desc: null
  value: 256-256
orthogonal_init:
  desc: null
  value: false
policy_log_std_multiplier:
  desc: null
  value: 1.0
policy_log_std_offset:
  desc: null
  value: -1.0
n_epochs:
  desc: null
  value: 1000
n_env_steps_per_epoch:
  desc: null
  value: 1000
n_train_step_per_epoch:
  desc: null
  value: 1000
eval_period:
  desc: null
  value: 10
eval_n_trajs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 256
sac.alpha_multiplier:
  desc: null
  value: 1.0
sac.backup_entropy:
  desc: null
  value: true
sac.discount:
  desc: null
  value: 0.99
sac.optimizer_type:
  desc: null
  value: adam
sac.policy_lr:
  desc: null
  value: 0.0003
sac.qf_lr:
  desc: null
  value: 0.0003
sac.reward_scale:
  desc: null
  value: 1.0
sac.soft_target_update_rate:
  desc: null
  value: 0.005
sac.target_entropy:
  desc: null
  value: 0.0
sac.target_update_period:
  desc: null
  value: 1
sac.use_automatic_entropy_tuning:
  desc: null
  value: true
logging.anonymous:
  desc: null
  value: null
logging.experiment_id:
  desc: null
  value: null
logging.notes:
  desc: null
  value: null
logging.online:
  desc: null
  value: true
logging.output_dir:
  desc: null
  value: ./experiment_output2
logging.prefix:
  desc: null
  value: SimpleSAC
logging.project:
  desc: null
  value: sac
logging.random_delay:
  desc: null
  value: 0.0
hostname:
  desc: null
  value: iotustc-PowerEdge-T630
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686150690.493825
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 14
      - 16
      - 23
      4: 3.7.16
      5: 0.15.2
      8:
      - 8
